ALTER TABLE socialraven.post
    ADD COLUMN IF NOT EXISTS failure_category VARCHAR(50),
    ADD COLUMN IF NOT EXISTS failure_confidence INTEGER,
    ADD COLUMN IF NOT EXISTS failure_summary VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS failure_raw_error VARCHAR(12000),
    ADD COLUMN IF NOT EXISTS provider_failure_evidence VARCHAR(12000),
    ADD COLUMN IF NOT EXISTS publish_retry_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS next_retry_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS last_failure_analyzed_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS user_notified_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS admin_notified_at TIMESTAMP WITH TIME ZONE;
